<?php

namespace Tritoq\Bundle\ManagerBoletoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoletoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletoRepository extends EntityRepository
{
}
